name: Python Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with flake8
      continue-on-error: true
      run: |
        flake8 app

    - name: Format with black
      run: |
        black app

    - name: Setup Git
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "action@github.com"

    - name: Detect changes and push
      run: |
        if [[ -n $(git diff --name-only) ]]; then
            echo "Se detectaron cambios:"
            git diff --name-only

            git add .
            git commit -m "Auto-commit: Cambios detectados"
            git push origin main
        else
            echo "No se detectaron cambios."
        fi