name: Lint and Format

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: write

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with flake8
      continue-on-error: true
      run: |
        flake8 app

    - name: Format with black
      run: |
        black app

    - name: Commit and push changes if detected
      run: |
        changes_detected=false
        if ! git diff --quiet; then
          changes_detected=true
        fi

        if [ "$changes_detected" = true ]; then
          git checkout -B ${GITHUB_HEAD_REF}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: format code according to pep8'
          git push
        else
          echo "No changes detected. Skipping commit and push."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
